// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxv4c9Mr2ddRXoQLq_l7kZq7_i067jdEw',
    appId: '1:162127967277:web:033b4f0b7474cfccc0f4a4',
    messagingSenderId: '162127967277',
    projectId: 'checkandgo-e1045',
    authDomain: 'checkandgo-e1045.firebaseapp.com',
    storageBucket: 'checkandgo-e1045.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOuaTAWUGlWw49IZwwVQ9fWrE3ywL5MqY',
    appId: '1:162127967277:ios:e1cf6a59ff2feed4c0f4a4',
    messagingSenderId: '162127967277',
    projectId: 'checkandgo-e1045',
    storageBucket: 'checkandgo-e1045.firebasestorage.app',
    iosBundleId: 'com.checkandgo.checkandgoApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_9ZFaxgZaUfw5oUEDJYB3qqiJiqdKsS8',
    appId: '1:162127967277:android:3dc448dd76b0b93bc0f4a4',
    messagingSenderId: '162127967277',
    projectId: 'checkandgo-e1045',
    storageBucket: 'checkandgo-e1045.firebasestorage.app',
  );

}